using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

/// <summary>
/// Экранная нижняя надпись для цепочки OCDMomentTrigger.
/// </summary>
public class OCDCaptionUI : MonoBehaviour
{
    [SerializeField] private CanvasGroup canvasGroup;
    [SerializeField] private TMP_Text captionText;
    [Header("Визуал (опционально)")]
    [Tooltip("Лёгкое затемнение нижней части экрана во время показа текста.")]
    [SerializeField] private Image bottomDimImage;
    [SerializeField, Range(0f, 1f)] private float bottomDimMaxAlpha = 0.7f;
    [Tooltip("Высота затемнения в долях высоты экрана (0..1).")]
    [SerializeField, Range(0.05f, 1f)] private float bottomDimHeight01 = 0.26f;
    [Tooltip("Смещение затемнения вниз (px). Отрицательное — ниже.")]
    [SerializeField] private float bottomDimYOffsetPx = -48f;

    private const int SortOrder = 10050;
    private const string SharedTextObjectName = "MessageText";
    private static OCDCaptionUI s_shared;
    private static bool s_creatingAutoOverlay;
    private bool _isAutoGenerated;
    private bool _fallbackUiBuilt;
    private Coroutine _routine;
    private static Sprite s_gradientSprite;
    private bool _messageTextStyleCaptured;
    private Color _savedColor;
    private Color32 _savedFaceColor;
    private Color32 _savedOutlineColor;
    private float _savedOutlineWidth;
    private bool _savedVertexGradient;
    private VertexGradient _savedColorGradient;
    private TMP_ColorGradient _savedColorGradientPreset;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
    private static void ResetStaticState()
    {
        s_shared = null;
    }

    static OCDCaptionUI()
    {
        SceneManager.sceneLoaded += (_, _) => s_shared = null;
    }

    public static OCDCaptionUI GetSharedOverlay()
    {
        if (s_shared != null)
            return s_shared;

        OCDCaptionUI existing = FindBestExisting();
        if (existing != null)
        {
            existing.ResolveReferences();
            existing.HideImmediate();
            s_shared = existing;
            return s_shared;
        }

        OCDCaptionUI fromNamed = AcquireFromNamedCaptionText();
        if (fromNamed != null)
        {
            fromNamed.ResolveReferences();
            fromNamed.HideImmediate();
            s_shared = fromNamed;
            return s_shared;
        }

        GameObject root = new GameObject("OCDCaptionUI_Auto");
        DontDestroyOnLoad(root);

        s_creatingAutoOverlay = true;
        try
        {
            s_shared = root.AddComponent<OCDCaptionUI>();
            s_shared._isAutoGenerated = true;
            s_shared.BuildFallbackUi();
            s_shared.HideImmediate();
        }
        finally
        {
            s_creatingAutoOverlay = false;
        }

        return s_shared;
    }

    private void Awake()
    {
        if (s_creatingAutoOverlay)
            return;

        ResolveReferences();
        CaptureMessageTextStyleIfNeeded();
        HideImmediate();
    }

    private void ResolveReferences()
    {
        if (canvasGroup == null)
            canvasGroup = GetComponent<CanvasGroup>();

        if (captionText == null)
            captionText = GetComponentInChildren<TMP_Text>(true);

        if (canvasGroup == null)
            canvasGroup = gameObject.AddComponent<CanvasGroup>();

        if (bottomDimImage == null)
            bottomDimImage = GetComponentInChildren<Image>(true);

        EnsureBottomDimExistsIfNeeded();
    }

    private static OCDCaptionUI FindBestExisting()
    {
        OCDCaptionUI[] all = Object.FindObjectsByType<OCDCaptionUI>(
            FindObjectsInactive.Include,
            FindObjectsSortMode.None);

        OCDCaptionUI underPlayer = null;
        OCDCaptionUI anyNonAuto = null;

        for (int i = 0; i < all.Length; i++)
        {
            OCDCaptionUI candidate = all[i];
            if (candidate == null)
                continue;

            if (!candidate._isAutoGenerated && anyNonAuto == null)
                anyNonAuto = candidate;

            if (IsUnderPlayerHierarchy(candidate.transform))
                underPlayer ??= candidate;
        }

        if (underPlayer != null && !underPlayer._isAutoGenerated)
            return underPlayer;

        if (anyNonAuto != null)
            return anyNonAuto;

        return underPlayer;
    }

    private static bool IsUnderPlayerHierarchy(Transform transform)
    {
        Transform current = transform;
        while (current != null)
        {
            if (current.CompareTag("Player"))
                return true;

            if (current.name.IndexOf("Player", System.StringComparison.OrdinalIgnoreCase) >= 0
                && current.GetComponentInParent<CharacterController>() != null)
                return true;

            current = current.parent;
        }

        return false;
    }

    private static OCDCaptionUI AcquireFromNamedCaptionText()
    {
        TMP_Text label = FindCaptionLabel();
        if (label == null)
            return null;

        GameObject go = label.gameObject;

        if (!go.TryGetComponent(out CanvasGroup group))
        {
            // CanvasGroup удобен для плавного появления/скрытия, как у PressEText.
            group = go.AddComponent<CanvasGroup>();
        }

        if (!go.TryGetComponent(out OCDCaptionUI ui))
            ui = go.AddComponent<OCDCaptionUI>();

        ui._isAutoGenerated = false;
        ui.canvasGroup = group;
        ui.captionText = label;
        ui.EnsureBottomDimExistsIfNeeded();
        ui.CaptureMessageTextStyleIfNeeded();
        return ui;
    }

    private static TMP_Text FindCaptionLabel()
    {
        TMP_Text[] all = Object.FindObjectsByType<TMP_Text>(
            FindObjectsInactive.Include,
            FindObjectsSortMode.None);

        TMP_Text fallbackUnderPlayer = null;

        for (int i = 0; i < all.Length; i++)
        {
            TMP_Text candidate = all[i];
            if (candidate == null)
                continue;

            string name = candidate.gameObject.name;
            if (name != SharedTextObjectName)
                continue;

            if (IsUnderPlayerHierarchy(candidate.transform))
            {
                fallbackUnderPlayer ??= candidate;
                continue;
            }

            return candidate;
        }

        return fallbackUnderPlayer;
    }

    private void EnsureBottomDimExistsIfNeeded()
    {
        if (bottomDimImage != null)
            return;

        // Если UI уже собран вручную (Player.prefab) — не трогаем.
        // Автогенерация затемнения только для авто-оверлея / автопривязки к MessageText.

        Transform parent = transform.parent != null ? transform.parent : transform;
        Canvas canvas = GetComponentInParent<Canvas>();
        if (canvas != null)
            parent = canvas.transform;

        GameObject dimGo = new GameObject("OCD_BottomDim");
        dimGo.transform.SetParent(parent, false);

        RectTransform rt = dimGo.AddComponent<RectTransform>();
        rt.anchorMin = new Vector2(0f, 0f);
        rt.anchorMax = new Vector2(1f, bottomDimHeight01);
        rt.pivot = new Vector2(0.5f, 0.5f);
        rt.anchoredPosition = new Vector2(0f, bottomDimYOffsetPx);
        rt.sizeDelta = Vector2.zero;

        Image img = dimGo.AddComponent<Image>();
        img.color = new Color(0f, 0f, 0f, 0f);
        img.raycastTarget = false;
        bottomDimImage = img;

        ConfigureGradient(bottomDimImage);
        dimGo.transform.SetSiblingIndex(0);
    }

    private static void ConfigureGradient(Image img)
    {
        if (img == null)
            return;

        if (s_gradientSprite == null)
            s_gradientSprite = BuildGradientSprite();

        img.sprite = s_gradientSprite;
        img.type = Image.Type.Simple;
        img.preserveAspect = false;
    }

    private static Sprite BuildGradientSprite()
    {
        const int height = 128;
        Texture2D tex = new Texture2D(1, height, TextureFormat.RGBA32, false, true);
        tex.wrapMode = TextureWrapMode.Clamp;
        tex.filterMode = FilterMode.Bilinear;

        for (int y = 0; y < height; y++)
        {
            float t = y / (height - 1f); // 0 bottom -> 1 top
            // Нелинейный градиент: плотнее снизу, мягче кверху.
            float a = 1f - Mathf.SmoothStep(0f, 1f, t);
            tex.SetPixel(0, y, new Color(1f, 1f, 1f, a));
        }

        tex.Apply(false, true);
        Rect r = new Rect(0, 0, 1, height);
        return Sprite.Create(tex, r, new Vector2(0.5f, 0f), pixelsPerUnit: 100f);
    }

    private void BuildFallbackUi()
    {
        if (_fallbackUiBuilt)
            return;

        if (!TryGetComponent(out Canvas _))
        {
            Canvas canvas = gameObject.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = SortOrder;

            CanvasScaler scaler = gameObject.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920, 1080);
            gameObject.AddComponent<GraphicRaycaster>();
        }

        EnsureCanvasGroup();
        if (canvasGroup == null)
        {
            Debug.LogError("OCDCaptionUI: не удалось создать CanvasGroup для оверлея подписи.", this);
            return;
        }

        canvasGroup.alpha = 0f;
        canvasGroup.interactable = false;
        canvasGroup.blocksRaycasts = false;

        GameObject bgGo = new GameObject("Background");
        bgGo.transform.SetParent(transform, false);
        RectTransform backgroundRect = bgGo.AddComponent<RectTransform>();
        backgroundRect.anchorMin = new Vector2(0f, 0f);
        backgroundRect.anchorMax = new Vector2(1f, 0f);
        backgroundRect.pivot = new Vector2(0.5f, 0f);
        backgroundRect.anchoredPosition = new Vector2(0f, 96f);
        backgroundRect.sizeDelta = new Vector2(0f, 160f);

        Image backgroundImage = bgGo.AddComponent<Image>();
        backgroundImage.color = new Color(0f, 0f, 0f, 0.55f);
        backgroundImage.raycastTarget = false;

        GameObject textGo = new GameObject("Caption");
        textGo.transform.SetParent(transform, false);
        RectTransform textRect = textGo.AddComponent<RectTransform>();
        textRect.anchorMin = new Vector2(0f, 0f);
        textRect.anchorMax = new Vector2(1f, 0f);
        textRect.pivot = new Vector2(0.5f, 0f);
        textRect.anchoredPosition = new Vector2(0f, 96f);
        textRect.sizeDelta = new Vector2(-240f, 160f);

        captionText = textGo.AddComponent<TextMeshProUGUI>();
        captionText.text = string.Empty;
        captionText.fontSize = 38f;
        captionText.alignment = TextAlignmentOptions.Center;
        captionText.color = Color.white;
        captionText.raycastTarget = false;
        captionText.enableWordWrapping = true;

        EnsureBottomDimExistsIfNeeded();
        _fallbackUiBuilt = true;
        gameObject.SetActive(false);
    }

    private void EnsureCanvasGroup()
    {
        if (canvasGroup != null)
            return;

        if (!TryGetComponent(out canvasGroup))
            canvasGroup = gameObject.AddComponent<CanvasGroup>();
    }

    public bool IsVisible => canvasGroup != null && canvasGroup.alpha > 0.01f;

    /// <summary>Не меняет MessageText — нижняя надпись сохраняет стиль Player MessageText.</summary>
    public void ApplyStyleFrom(TMP_Text reference)
    {
        ResolveReferences();
        CaptureMessageTextStyleIfNeeded();
    }

    private void CaptureMessageTextStyleIfNeeded()
    {
        if (_messageTextStyleCaptured || captionText == null)
            return;

        if (!IsPlayerMessageText(captionText))
            return;

        _savedColor = captionText.color;
        _savedFaceColor = captionText.faceColor;
        _savedOutlineColor = captionText.outlineColor;
        _savedOutlineWidth = captionText.outlineWidth;
        _savedVertexGradient = captionText.enableVertexGradient;
        _savedColorGradient = captionText.colorGradient;
        _savedColorGradientPreset = captionText.colorGradientPreset;
        _messageTextStyleCaptured = true;
    }

    private void RestoreMessageTextStyle()
    {
        CaptureMessageTextStyleIfNeeded();
        if (!_messageTextStyleCaptured || captionText == null)
            return;

        captionText.color = _savedColor;
        captionText.faceColor = _savedFaceColor;
        captionText.outlineColor = _savedOutlineColor;
        captionText.outlineWidth = _savedOutlineWidth;
        captionText.enableVertexGradient = _savedVertexGradient;
        captionText.colorGradient = _savedColorGradient;
        captionText.colorGradientPreset = _savedColorGradientPreset;
    }

    private static bool IsPlayerMessageText(TMP_Text text)
    {
        return text != null && text.gameObject.name == SharedTextObjectName;
    }

    public IEnumerator ShowRoutine(string text, float fadeInDuration, float holdDuration, float fadeOutDuration)
    {
        yield return ShowCaptionFadeIn(text, fadeInDuration);
        yield return CaptionHoldAndFadeOut(holdDuration, fadeOutDuration);
    }

    /// <summary>Плавное появление нижней надписи (без удержания и скрытия).</summary>
    public IEnumerator ShowCaptionFadeIn(string text, float fadeInDuration)
    {
        if (!PrepareCaptionShow(text))
            yield break;

        float fadeIn = Mathf.Max(0.01f, fadeInDuration);
        yield return FadeAlpha(0f, 1f, fadeIn);
    }

    /// <summary>Удержание и скрытие подписи (можно запустить в фоне).</summary>
    public IEnumerator CaptionHoldAndFadeOut(float holdDuration, float fadeOutDuration)
    {
        if (captionText == null || canvasGroup == null)
            yield break;

        if (holdDuration > 0f)
            yield return new WaitForSecondsRealtime(holdDuration);

        float fadeOut = Mathf.Max(0.01f, fadeOutDuration);
        yield return FadeAlpha(canvasGroup.alpha, 0f, fadeOut);

        canvasGroup.alpha = 0f;
        ApplyBottomDimAlpha(0f);

        SetHiddenState();
    }

    public void RunCaptionHoldAndFadeOut(float holdDuration, float fadeOutDuration)
    {
        if (captionText == null || canvasGroup == null)
            return;

        if (_routine != null)
            StopCoroutine(_routine);

        EnsureActiveForCoroutines();
        _routine = StartCoroutine(CaptionHoldAndFadeOutAndClearRoutine(holdDuration, fadeOutDuration));
    }

    private IEnumerator CaptionHoldAndFadeOutAndClearRoutine(float holdDuration, float fadeOutDuration)
    {
        yield return CaptionHoldAndFadeOut(holdDuration, fadeOutDuration);
        _routine = null;
    }

    private bool PrepareCaptionShow(string text)
    {
        if (_isAutoGenerated && !_fallbackUiBuilt)
            BuildFallbackUi();

        ResolveReferences();
        RestoreMessageTextStyle();

        if (captionText == null || canvasGroup == null)
        {
            Debug.LogWarning("OCDCaptionUI: нет UI для показа подписи.", this);
            return false;
        }

        if (_routine != null)
            StopCoroutine(_routine);

        captionText.text = text ?? string.Empty;
        captionText.ForceMeshUpdate();

        EnsureActiveForCoroutines();
        canvasGroup.interactable = false;
        canvasGroup.blocksRaycasts = false;
        canvasGroup.alpha = 0f;
        ApplyBottomDimAlpha(0f);
        return true;
    }

    public void HideImmediate()
    {
        ResolveReferences();

        SetHiddenState();
    }

    public IEnumerator HideSmooth(float duration)
    {
        ResolveReferences();

        if (!IsVisible)
            yield break;

        float d = Mathf.Max(0.01f, duration);
        yield return FadeAlpha(canvasGroup.alpha, 0f, d);
        SetHiddenState();
    }

    private void EnsureActiveForCoroutines()
    {
        if (!gameObject.activeInHierarchy)
            gameObject.SetActive(true);
    }

    private void SetHiddenState()
    {
        ResolveReferences();

        if (canvasGroup != null)
        {
            canvasGroup.alpha = 0f;
            canvasGroup.interactable = false;
            canvasGroup.blocksRaycasts = false;
        }

        ApplyBottomDimAlpha(0f);
    }

    private IEnumerator FadeAlpha(float from, float to, float duration)
    {
        float elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.unscaledDeltaTime;
            float a = Mathf.Lerp(from, to, Mathf.Clamp01(elapsed / duration));
            canvasGroup.alpha = a;
            ApplyBottomDimAlpha(a);
            yield return null;
        }

        canvasGroup.alpha = to;
        ApplyBottomDimAlpha(to);
    }

    private void ApplyBottomDimAlpha(float captionAlpha01)
    {
        if (bottomDimImage == null)
            return;

        Color c = bottomDimImage.color;
        c.a = Mathf.Clamp01(bottomDimMaxAlpha) * Mathf.Clamp01(captionAlpha01);
        bottomDimImage.color = c;
    }
}

